/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderIdRouteImport } from './routes/$providerId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIdIndexRouteImport } from './routes/$providerId/index'
import { Route as ProviderIdRegisterRouteImport } from './routes/$providerId/register'
import { Route as ProviderIdLoginRouteImport } from './routes/$providerId/login'
import { Route as ProviderIdAccountRouteImport } from './routes/$providerId/account'
import { Route as ProviderIdServerSlugRouteImport } from './routes/$providerId/$serverSlug'
import { Route as ProviderIdServerSlugIndexRouteImport } from './routes/$providerId/$serverSlug/index'
import { Route as ProviderIdServerSlugSettingsRouteImport } from './routes/$providerId/$serverSlug/settings'
import { Route as ProviderIdServerSlugChannelIdRouteImport } from './routes/$providerId/$serverSlug/$channelId'

const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdIndexRoute = ProviderIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdRegisterRoute = ProviderIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdLoginRoute = ProviderIdLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdAccountRoute = ProviderIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdServerSlugRoute = ProviderIdServerSlugRouteImport.update({
  id: '/$serverSlug',
  path: '/$serverSlug',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdServerSlugIndexRoute =
  ProviderIdServerSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProviderIdServerSlugRoute,
  } as any)
const ProviderIdServerSlugSettingsRoute =
  ProviderIdServerSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProviderIdServerSlugRoute,
  } as any)
const ProviderIdServerSlugChannelIdRoute =
  ProviderIdServerSlugChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => ProviderIdServerSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$providerId': typeof ProviderIdRouteWithChildren
  '/$providerId/$serverSlug': typeof ProviderIdServerSlugRouteWithChildren
  '/$providerId/account': typeof ProviderIdAccountRoute
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId/': typeof ProviderIdIndexRoute
  '/$providerId/$serverSlug/$channelId': typeof ProviderIdServerSlugChannelIdRoute
  '/$providerId/$serverSlug/settings': typeof ProviderIdServerSlugSettingsRoute
  '/$providerId/$serverSlug/': typeof ProviderIdServerSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$providerId/account': typeof ProviderIdAccountRoute
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId': typeof ProviderIdIndexRoute
  '/$providerId/$serverSlug/$channelId': typeof ProviderIdServerSlugChannelIdRoute
  '/$providerId/$serverSlug/settings': typeof ProviderIdServerSlugSettingsRoute
  '/$providerId/$serverSlug': typeof ProviderIdServerSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$providerId': typeof ProviderIdRouteWithChildren
  '/$providerId/$serverSlug': typeof ProviderIdServerSlugRouteWithChildren
  '/$providerId/account': typeof ProviderIdAccountRoute
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId/': typeof ProviderIdIndexRoute
  '/$providerId/$serverSlug/$channelId': typeof ProviderIdServerSlugChannelIdRoute
  '/$providerId/$serverSlug/settings': typeof ProviderIdServerSlugSettingsRoute
  '/$providerId/$serverSlug/': typeof ProviderIdServerSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$providerId'
    | '/$providerId/$serverSlug'
    | '/$providerId/account'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId/'
    | '/$providerId/$serverSlug/$channelId'
    | '/$providerId/$serverSlug/settings'
    | '/$providerId/$serverSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$providerId/account'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId'
    | '/$providerId/$serverSlug/$channelId'
    | '/$providerId/$serverSlug/settings'
    | '/$providerId/$serverSlug'
  id:
    | '__root__'
    | '/'
    | '/$providerId'
    | '/$providerId/$serverSlug'
    | '/$providerId/account'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId/'
    | '/$providerId/$serverSlug/$channelId'
    | '/$providerId/$serverSlug/settings'
    | '/$providerId/$serverSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProviderIdRoute: typeof ProviderIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$providerId': {
      id: '/$providerId'
      path: '/$providerId'
      fullPath: '/$providerId'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$providerId/': {
      id: '/$providerId/'
      path: '/'
      fullPath: '/$providerId/'
      preLoaderRoute: typeof ProviderIdIndexRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/register': {
      id: '/$providerId/register'
      path: '/register'
      fullPath: '/$providerId/register'
      preLoaderRoute: typeof ProviderIdRegisterRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/login': {
      id: '/$providerId/login'
      path: '/login'
      fullPath: '/$providerId/login'
      preLoaderRoute: typeof ProviderIdLoginRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/account': {
      id: '/$providerId/account'
      path: '/account'
      fullPath: '/$providerId/account'
      preLoaderRoute: typeof ProviderIdAccountRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/$serverSlug': {
      id: '/$providerId/$serverSlug'
      path: '/$serverSlug'
      fullPath: '/$providerId/$serverSlug'
      preLoaderRoute: typeof ProviderIdServerSlugRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/$serverSlug/': {
      id: '/$providerId/$serverSlug/'
      path: '/'
      fullPath: '/$providerId/$serverSlug/'
      preLoaderRoute: typeof ProviderIdServerSlugIndexRouteImport
      parentRoute: typeof ProviderIdServerSlugRoute
    }
    '/$providerId/$serverSlug/settings': {
      id: '/$providerId/$serverSlug/settings'
      path: '/settings'
      fullPath: '/$providerId/$serverSlug/settings'
      preLoaderRoute: typeof ProviderIdServerSlugSettingsRouteImport
      parentRoute: typeof ProviderIdServerSlugRoute
    }
    '/$providerId/$serverSlug/$channelId': {
      id: '/$providerId/$serverSlug/$channelId'
      path: '/$channelId'
      fullPath: '/$providerId/$serverSlug/$channelId'
      preLoaderRoute: typeof ProviderIdServerSlugChannelIdRouteImport
      parentRoute: typeof ProviderIdServerSlugRoute
    }
  }
}

interface ProviderIdServerSlugRouteChildren {
  ProviderIdServerSlugChannelIdRoute: typeof ProviderIdServerSlugChannelIdRoute
  ProviderIdServerSlugSettingsRoute: typeof ProviderIdServerSlugSettingsRoute
  ProviderIdServerSlugIndexRoute: typeof ProviderIdServerSlugIndexRoute
}

const ProviderIdServerSlugRouteChildren: ProviderIdServerSlugRouteChildren = {
  ProviderIdServerSlugChannelIdRoute: ProviderIdServerSlugChannelIdRoute,
  ProviderIdServerSlugSettingsRoute: ProviderIdServerSlugSettingsRoute,
  ProviderIdServerSlugIndexRoute: ProviderIdServerSlugIndexRoute,
}

const ProviderIdServerSlugRouteWithChildren =
  ProviderIdServerSlugRoute._addFileChildren(ProviderIdServerSlugRouteChildren)

interface ProviderIdRouteChildren {
  ProviderIdServerSlugRoute: typeof ProviderIdServerSlugRouteWithChildren
  ProviderIdAccountRoute: typeof ProviderIdAccountRoute
  ProviderIdLoginRoute: typeof ProviderIdLoginRoute
  ProviderIdRegisterRoute: typeof ProviderIdRegisterRoute
  ProviderIdIndexRoute: typeof ProviderIdIndexRoute
}

const ProviderIdRouteChildren: ProviderIdRouteChildren = {
  ProviderIdServerSlugRoute: ProviderIdServerSlugRouteWithChildren,
  ProviderIdAccountRoute: ProviderIdAccountRoute,
  ProviderIdLoginRoute: ProviderIdLoginRoute,
  ProviderIdRegisterRoute: ProviderIdRegisterRoute,
  ProviderIdIndexRoute: ProviderIdIndexRoute,
}

const ProviderIdRouteWithChildren = ProviderIdRoute._addFileChildren(
  ProviderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProviderIdRoute: ProviderIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
