/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderIdRouteImport } from './routes/$providerId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIdRegisterRouteImport } from './routes/$providerId/register'
import { Route as ProviderIdLoginRouteImport } from './routes/$providerId/login'
import { Route as ProviderIdDashboardRouteImport } from './routes/$providerId/dashboard'
import { Route as ProviderIdDashboardServerIdRouteImport } from './routes/$providerId/dashboard.$serverId'
import { Route as ProviderIdDashboardServerIdChannelIdRouteImport } from './routes/$providerId/dashboard.$serverId.$channelId'

const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRegisterRoute = ProviderIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdLoginRoute = ProviderIdLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdDashboardRoute = ProviderIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProviderIdRoute,
} as any)
const ProviderIdDashboardServerIdRoute =
  ProviderIdDashboardServerIdRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => ProviderIdDashboardRoute,
  } as any)
const ProviderIdDashboardServerIdChannelIdRoute =
  ProviderIdDashboardServerIdChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => ProviderIdDashboardServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$providerId': typeof ProviderIdRouteWithChildren
  '/$providerId/dashboard': typeof ProviderIdDashboardRouteWithChildren
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId/dashboard/$serverId': typeof ProviderIdDashboardServerIdRouteWithChildren
  '/$providerId/dashboard/$serverId/$channelId': typeof ProviderIdDashboardServerIdChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$providerId': typeof ProviderIdRouteWithChildren
  '/$providerId/dashboard': typeof ProviderIdDashboardRouteWithChildren
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId/dashboard/$serverId': typeof ProviderIdDashboardServerIdRouteWithChildren
  '/$providerId/dashboard/$serverId/$channelId': typeof ProviderIdDashboardServerIdChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$providerId': typeof ProviderIdRouteWithChildren
  '/$providerId/dashboard': typeof ProviderIdDashboardRouteWithChildren
  '/$providerId/login': typeof ProviderIdLoginRoute
  '/$providerId/register': typeof ProviderIdRegisterRoute
  '/$providerId/dashboard/$serverId': typeof ProviderIdDashboardServerIdRouteWithChildren
  '/$providerId/dashboard/$serverId/$channelId': typeof ProviderIdDashboardServerIdChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$providerId'
    | '/$providerId/dashboard'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId/dashboard/$serverId'
    | '/$providerId/dashboard/$serverId/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$providerId'
    | '/$providerId/dashboard'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId/dashboard/$serverId'
    | '/$providerId/dashboard/$serverId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/$providerId'
    | '/$providerId/dashboard'
    | '/$providerId/login'
    | '/$providerId/register'
    | '/$providerId/dashboard/$serverId'
    | '/$providerId/dashboard/$serverId/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProviderIdRoute: typeof ProviderIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$providerId': {
      id: '/$providerId'
      path: '/$providerId'
      fullPath: '/$providerId'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$providerId/register': {
      id: '/$providerId/register'
      path: '/register'
      fullPath: '/$providerId/register'
      preLoaderRoute: typeof ProviderIdRegisterRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/login': {
      id: '/$providerId/login'
      path: '/login'
      fullPath: '/$providerId/login'
      preLoaderRoute: typeof ProviderIdLoginRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/dashboard': {
      id: '/$providerId/dashboard'
      path: '/dashboard'
      fullPath: '/$providerId/dashboard'
      preLoaderRoute: typeof ProviderIdDashboardRouteImport
      parentRoute: typeof ProviderIdRoute
    }
    '/$providerId/dashboard/$serverId': {
      id: '/$providerId/dashboard/$serverId'
      path: '/$serverId'
      fullPath: '/$providerId/dashboard/$serverId'
      preLoaderRoute: typeof ProviderIdDashboardServerIdRouteImport
      parentRoute: typeof ProviderIdDashboardRoute
    }
    '/$providerId/dashboard/$serverId/$channelId': {
      id: '/$providerId/dashboard/$serverId/$channelId'
      path: '/$channelId'
      fullPath: '/$providerId/dashboard/$serverId/$channelId'
      preLoaderRoute: typeof ProviderIdDashboardServerIdChannelIdRouteImport
      parentRoute: typeof ProviderIdDashboardServerIdRoute
    }
  }
}

interface ProviderIdDashboardServerIdRouteChildren {
  ProviderIdDashboardServerIdChannelIdRoute: typeof ProviderIdDashboardServerIdChannelIdRoute
}

const ProviderIdDashboardServerIdRouteChildren: ProviderIdDashboardServerIdRouteChildren =
  {
    ProviderIdDashboardServerIdChannelIdRoute:
      ProviderIdDashboardServerIdChannelIdRoute,
  }

const ProviderIdDashboardServerIdRouteWithChildren =
  ProviderIdDashboardServerIdRoute._addFileChildren(
    ProviderIdDashboardServerIdRouteChildren,
  )

interface ProviderIdDashboardRouteChildren {
  ProviderIdDashboardServerIdRoute: typeof ProviderIdDashboardServerIdRouteWithChildren
}

const ProviderIdDashboardRouteChildren: ProviderIdDashboardRouteChildren = {
  ProviderIdDashboardServerIdRoute:
    ProviderIdDashboardServerIdRouteWithChildren,
}

const ProviderIdDashboardRouteWithChildren =
  ProviderIdDashboardRoute._addFileChildren(ProviderIdDashboardRouteChildren)

interface ProviderIdRouteChildren {
  ProviderIdDashboardRoute: typeof ProviderIdDashboardRouteWithChildren
  ProviderIdLoginRoute: typeof ProviderIdLoginRoute
  ProviderIdRegisterRoute: typeof ProviderIdRegisterRoute
}

const ProviderIdRouteChildren: ProviderIdRouteChildren = {
  ProviderIdDashboardRoute: ProviderIdDashboardRouteWithChildren,
  ProviderIdLoginRoute: ProviderIdLoginRoute,
  ProviderIdRegisterRoute: ProviderIdRegisterRoute,
}

const ProviderIdRouteWithChildren = ProviderIdRoute._addFileChildren(
  ProviderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProviderIdRoute: ProviderIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
