/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardServerIdRouteImport } from './routes/dashboard.$serverId'
import { Route as DashboardServerIdChannelIdRouteImport } from './routes/dashboard.$serverId.$channelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServerIdRoute = DashboardServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServerIdChannelIdRoute =
  DashboardServerIdChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => DashboardServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$serverId': typeof DashboardServerIdRouteWithChildren
  '/dashboard/$serverId/$channelId': typeof DashboardServerIdChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$serverId': typeof DashboardServerIdRouteWithChildren
  '/dashboard/$serverId/$channelId': typeof DashboardServerIdChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$serverId': typeof DashboardServerIdRouteWithChildren
  '/dashboard/$serverId/$channelId': typeof DashboardServerIdChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/$serverId'
    | '/dashboard/$serverId/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/$serverId'
    | '/dashboard/$serverId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/$serverId'
    | '/dashboard/$serverId/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$serverId': {
      id: '/dashboard/$serverId'
      path: '/$serverId'
      fullPath: '/dashboard/$serverId'
      preLoaderRoute: typeof DashboardServerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$serverId/$channelId': {
      id: '/dashboard/$serverId/$channelId'
      path: '/$channelId'
      fullPath: '/dashboard/$serverId/$channelId'
      preLoaderRoute: typeof DashboardServerIdChannelIdRouteImport
      parentRoute: typeof DashboardServerIdRoute
    }
  }
}

interface DashboardServerIdRouteChildren {
  DashboardServerIdChannelIdRoute: typeof DashboardServerIdChannelIdRoute
}

const DashboardServerIdRouteChildren: DashboardServerIdRouteChildren = {
  DashboardServerIdChannelIdRoute: DashboardServerIdChannelIdRoute,
}

const DashboardServerIdRouteWithChildren =
  DashboardServerIdRoute._addFileChildren(DashboardServerIdRouteChildren)

interface DashboardRouteChildren {
  DashboardServerIdRoute: typeof DashboardServerIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardServerIdRoute: DashboardServerIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
