// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type { Client, Options as Options2, TDataShape } from "./client/index.js";
import type {
  GetApiChannelsByChannelIdMessagesData,
  GetApiChannelsByChannelIdMessagesResponses,
  GetApiData,
  GetApiMessagesByMessageIdThreadData,
  GetApiMessagesByMessageIdThreadResponses,
  GetApiResponses,
  GetApiServersByServerIdAgentsData,
  GetApiServersByServerIdAgentsResponses,
  GetApiServersByServerIdChannelsData,
  GetApiServersByServerIdChannelsResponses,
  GetApiServersData,
  GetApiServersResponses,
  PostApiAgentsRegisterData,
  PostApiAgentsRegisterErrors,
  PostApiAgentsRegisterResponses,
  PostApiChannelsByChannelIdMessagesData,
  PostApiChannelsByChannelIdMessagesErrors,
  PostApiChannelsByChannelIdMessagesResponses,
  PostApiMachinesByMachineIdRevokeData,
  PostApiMachinesByMachineIdRevokeResponses,
  PostApiMachinesRegisterData,
  PostApiMachinesRegisterErrors,
  PostApiMachinesRegisterResponses,
  PostApiServersByServerIdChannelsData,
  PostApiServersByServerIdChannelsErrors,
  PostApiServersByServerIdChannelsResponses,
  PostApiServersData,
  PostApiServersErrors,
  PostApiServersResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * API 根目录
 *
 * 用于测试 API 连通性
 */
export const getApi = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiResponses, unknown, ThrowOnError>({
    url: "/api",
    ...options,
  });

/**
 * 获取服务器列表
 *
 * 获取当前用户参与的所有服务器空间
 */
export const getApiServers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiServersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiServersResponses, unknown, ThrowOnError>({
    url: "/api/servers",
    ...options,
  });

/**
 * 创建服务器
 *
 * 创建一个新的频道服务器空间，并将创建者归为管理员成员
 */
export const postApiServers = <ThrowOnError extends boolean = false>(
  options: Options<PostApiServersData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiServersResponses, PostApiServersErrors, ThrowOnError>({
    url: "/api/servers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取频道列表
 *
 * 获取指定服务器空间内的所有文字聊天频道
 */
export const getApiServersByServerIdChannels = <ThrowOnError extends boolean = false>(
  options: Options<GetApiServersByServerIdChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiServersByServerIdChannelsResponses, unknown, ThrowOnError>({
    url: "/api/servers/{serverId}/channels",
    ...options,
  });

/**
 * 创建频道
 *
 * 在指定服务器中创建一个新的文本对话频道
 */
export const postApiServersByServerIdChannels = <ThrowOnError extends boolean = false>(
  options: Options<PostApiServersByServerIdChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiServersByServerIdChannelsResponses,
    PostApiServersByServerIdChannelsErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}/channels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 注册受控物理机器机台
 *
 * 在所属的服务器空间下新注册一个工作机器实例，并发放 Machine 校验主密钥 （sk_slock_*）
 */
export const postApiMachinesRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiMachinesRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiMachinesRegisterResponses,
    PostApiMachinesRegisterErrors,
    ThrowOnError
  >({
    url: "/api/machines/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 吊销物理机台
 *
 * 吊销指定物理机台的鉴权凭证
 */
export const postApiMachinesByMachineIdRevoke = <ThrowOnError extends boolean = false>(
  options: Options<PostApiMachinesByMachineIdRevokeData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiMachinesByMachineIdRevokeResponses, unknown, ThrowOnError>(
    { url: "/api/machines/{machineId}/revoke", ...options },
  );

/**
 * 获取机器下的智能体列表
 *
 * 获取绑定在特定服务器空间的所有智能体实例
 */
export const getApiServersByServerIdAgents = <ThrowOnError extends boolean = false>(
  options: Options<GetApiServersByServerIdAgentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiServersByServerIdAgentsResponses, unknown, ThrowOnError>({
    url: "/api/servers/{serverId}/agents",
    ...options,
  });

/**
 * 注册智能体
 *
 * 由绑定在目标服务器机台上的运行守护进程上报并注册/更新智能体实例
 */
export const postApiAgentsRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAgentsRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAgentsRegisterResponses,
    PostApiAgentsRegisterErrors,
    ThrowOnError
  >({
    url: "/api/agents/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取频道消息
 *
 * 获取特定聊天频道内的历史消息消息列表
 */
export const getApiChannelsByChannelIdMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetApiChannelsByChannelIdMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiChannelsByChannelIdMessagesResponses, unknown, ThrowOnError>(
    { url: "/api/channels/{channelId}/messages", ...options },
  );

/**
 * 发送频道消息
 *
 * 在指定频道中发送文本消息内容，可附带父级节点及 Mentions 信息
 */
export const postApiChannelsByChannelIdMessages = <ThrowOnError extends boolean = false>(
  options: Options<PostApiChannelsByChannelIdMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiChannelsByChannelIdMessagesResponses,
    PostApiChannelsByChannelIdMessagesErrors,
    ThrowOnError
  >({
    url: "/api/channels/{channelId}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取消息会话线程
 *
 * 获取针对单条消息展开的回复会话链
 */
export const getApiMessagesByMessageIdThread = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMessagesByMessageIdThreadData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiMessagesByMessageIdThreadResponses, unknown, ThrowOnError>({
    url: "/api/messages/{messageId}/thread",
    ...options,
  });
