// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type { Client, Options as Options2, TDataShape } from "./client/index.js";
import type {
  ChangeEmailData,
  ChangeEmailErrors,
  ChangeEmailResponses,
  ChangePasswordData,
  ChangePasswordErrors,
  ChangePasswordResponses,
  DeleteApiChannelGroupsByGroupIdData,
  DeleteApiChannelGroupsByGroupIdErrors,
  DeleteApiChannelGroupsByGroupIdResponses,
  DeleteApiChannelsByChannelIdData,
  DeleteApiChannelsByChannelIdErrors,
  DeleteApiChannelsByChannelIdResponses,
  DeleteApiServersByServerIdData,
  DeleteApiServersByServerIdErrors,
  DeleteApiServersByServerIdResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  GetApiAuthAccountInfoData,
  GetApiAuthAccountInfoErrors,
  GetApiAuthAccountInfoResponses,
  GetApiAuthCallbackByIdData,
  GetApiAuthCallbackByIdErrors,
  GetApiAuthDeleteUserCallbackData,
  GetApiAuthDeleteUserCallbackErrors,
  GetApiAuthDeleteUserCallbackResponses,
  GetApiAuthErrorData,
  GetApiAuthErrorErrors,
  GetApiAuthErrorResponses,
  GetApiAuthOkData,
  GetApiAuthOkErrors,
  GetApiAuthOkResponses,
  GetApiAuthVerifyEmailData,
  GetApiAuthVerifyEmailErrors,
  GetApiAuthVerifyEmailResponses,
  GetApiChannelsByChannelIdMessagesData,
  GetApiChannelsByChannelIdMessagesResponses,
  GetApiData,
  GetApiMessagesByMessageIdThreadData,
  GetApiMessagesByMessageIdThreadResponses,
  GetApiResponses,
  GetApiServersByServerIdAgentsData,
  GetApiServersByServerIdAgentsResponses,
  GetApiServersByServerIdChannelGroupsData,
  GetApiServersByServerIdChannelGroupsErrors,
  GetApiServersByServerIdChannelGroupsResponses,
  GetApiServersByServerIdChannelsData,
  GetApiServersByServerIdChannelsResponses,
  GetApiServersData,
  GetApiServersResponses,
  GetSession2Data,
  GetSession2Errors,
  GetSession2Responses,
  GetSessionData,
  GetSessionErrors,
  GetSessionResponses,
  LinkSocialAccountData,
  LinkSocialAccountErrors,
  LinkSocialAccountResponses,
  ListUserAccountsData,
  ListUserAccountsErrors,
  ListUserAccountsResponses,
  ListUserSessionsData,
  ListUserSessionsErrors,
  ListUserSessionsResponses,
  PostApiAgentsRegisterData,
  PostApiAgentsRegisterErrors,
  PostApiAgentsRegisterResponses,
  PostApiAuthCallbackByIdData,
  PostApiAuthCallbackByIdErrors,
  PostApiAuthGetAccessTokenData,
  PostApiAuthGetAccessTokenErrors,
  PostApiAuthGetAccessTokenResponses,
  PostApiAuthRefreshTokenData,
  PostApiAuthRefreshTokenErrors,
  PostApiAuthRefreshTokenResponses,
  PostApiAuthRevokeOtherSessionsData,
  PostApiAuthRevokeOtherSessionsErrors,
  PostApiAuthRevokeOtherSessionsResponses,
  PostApiAuthRevokeSessionData,
  PostApiAuthRevokeSessionErrors,
  PostApiAuthRevokeSessionResponses,
  PostApiAuthRevokeSessionsData,
  PostApiAuthRevokeSessionsErrors,
  PostApiAuthRevokeSessionsResponses,
  PostApiAuthUnlinkAccountData,
  PostApiAuthUnlinkAccountErrors,
  PostApiAuthUnlinkAccountResponses,
  PostApiChannelsByChannelIdMessagesData,
  PostApiChannelsByChannelIdMessagesErrors,
  PostApiChannelsByChannelIdMessagesResponses,
  PostApiMachinesByMachineIdRevokeData,
  PostApiMachinesByMachineIdRevokeResponses,
  PostApiMachinesRegisterData,
  PostApiMachinesRegisterErrors,
  PostApiMachinesRegisterResponses,
  PostApiServersByServerIdChannelGroupsData,
  PostApiServersByServerIdChannelGroupsErrors,
  PostApiServersByServerIdChannelGroupsResponses,
  PostApiServersByServerIdChannelsData,
  PostApiServersByServerIdChannelsErrors,
  PostApiServersByServerIdChannelsResponses,
  PostApiServersData,
  PostApiServersErrors,
  PostApiServersResponses,
  PutApiChannelGroupsByGroupIdData,
  PutApiChannelGroupsByGroupIdErrors,
  PutApiChannelGroupsByGroupIdResponses,
  PutApiChannelsByChannelIdData,
  PutApiChannelsByChannelIdErrors,
  PutApiChannelsByChannelIdResponses,
  PutApiServersByServerIdChannelGroupsSortData,
  PutApiServersByServerIdChannelGroupsSortErrors,
  PutApiServersByServerIdChannelGroupsSortResponses,
  PutApiServersByServerIdChannelsSortData,
  PutApiServersByServerIdChannelsSortErrors,
  PutApiServersByServerIdChannelsSortResponses,
  PutApiServersByServerIdData,
  PutApiServersByServerIdErrors,
  PutApiServersByServerIdResponses,
  RequestPasswordResetData,
  RequestPasswordResetErrors,
  RequestPasswordResetResponses,
  ResetPasswordCallbackData,
  ResetPasswordCallbackErrors,
  ResetPasswordCallbackResponses,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  SendVerificationEmailData,
  SendVerificationEmailErrors,
  SendVerificationEmailResponses,
  SignInEmailData,
  SignInEmailErrors,
  SignInEmailResponses,
  SignOutData,
  SignOutErrors,
  SignOutResponses,
  SignUpWithEmailAndPasswordData,
  SignUpWithEmailAndPasswordErrors,
  SignUpWithEmailAndPasswordResponses,
  SocialSignInData,
  SocialSignInErrors,
  SocialSignInResponses,
  UpdateSessionData,
  UpdateSessionErrors,
  UpdateSessionResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  VerifyPasswordData,
  VerifyPasswordErrors,
  VerifyPasswordResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * API 根目录
 *
 * 用于测试 API 连通性
 */
export const getApi = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiResponses, unknown, ThrowOnError>({
    url: "/api",
    ...options,
  });

/**
 * 获取服务器列表
 *
 * 获取当前用户参与的所有服务器空间
 */
export const getApiServers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiServersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiServersResponses, unknown, ThrowOnError>({
    url: "/api/servers",
    ...options,
  });

/**
 * 创建服务器
 *
 * 创建一个新的频道服务器空间，并将创建者归为管理员成员
 */
export const postApiServers = <ThrowOnError extends boolean = false>(
  options: Options<PostApiServersData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiServersResponses, PostApiServersErrors, ThrowOnError>({
    url: "/api/servers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 删除服务器
 *
 * 级联物理删除特定的频道工作服务器空间
 */
export const deleteApiServersByServerId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiServersByServerIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiServersByServerIdResponses,
    DeleteApiServersByServerIdErrors,
    ThrowOnError
  >({ url: "/api/servers/{serverId}", ...options });

/**
 * 更新服务器
 *
 * 更新指定服务器的信息（例如修改显示名称或Slug）
 */
export const putApiServersByServerId = <ThrowOnError extends boolean = false>(
  options: Options<PutApiServersByServerIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiServersByServerIdResponses,
    PutApiServersByServerIdErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取频道列表
 *
 * 获取指定服务器空间内的所有文字聊天频道（支持排序和归档过滤）
 */
export const getApiServersByServerIdChannels = <ThrowOnError extends boolean = false>(
  options: Options<GetApiServersByServerIdChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiServersByServerIdChannelsResponses, unknown, ThrowOnError>({
    url: "/api/servers/{serverId}/channels",
    ...options,
  });

/**
 * 创建频道
 *
 * 在指定服务器中创建一个新的文本对话频道
 */
export const postApiServersByServerIdChannels = <ThrowOnError extends boolean = false>(
  options: Options<PostApiServersByServerIdChannelsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiServersByServerIdChannelsResponses,
    PostApiServersByServerIdChannelsErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}/channels",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 硬删除频道
 *
 * 物理删除特定的单条文字聊天频道及级联消息
 */
export const deleteApiChannelsByChannelId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiChannelsByChannelIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiChannelsByChannelIdResponses,
    DeleteApiChannelsByChannelIdErrors,
    ThrowOnError
  >({ url: "/api/channels/{channelId}", ...options });

/**
 * 更新频道
 *
 * 更新指定频道的配置、修改排序索引或切换归档（假删除）/解档状态
 */
export const putApiChannelsByChannelId = <ThrowOnError extends boolean = false>(
  options: Options<PutApiChannelsByChannelIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiChannelsByChannelIdResponses,
    PutApiChannelsByChannelIdErrors,
    ThrowOnError
  >({
    url: "/api/channels/{channelId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 批量排序频道
 *
 * 对指定服务器下的多个频道进行批量排序与所属分组调整
 */
export const putApiServersByServerIdChannelsSort = <ThrowOnError extends boolean = false>(
  options: Options<PutApiServersByServerIdChannelsSortData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiServersByServerIdChannelsSortResponses,
    PutApiServersByServerIdChannelsSortErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}/channels/sort",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取分组及嵌套频道列表
 *
 * 获取指定服务器空间内的所有频道分组，及其包含的活动聊天频道
 */
export const getApiServersByServerIdChannelGroups = <ThrowOnError extends boolean = false>(
  options: Options<GetApiServersByServerIdChannelGroupsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiServersByServerIdChannelGroupsResponses,
    GetApiServersByServerIdChannelGroupsErrors,
    ThrowOnError
  >({ url: "/api/servers/{serverId}/channel-groups", ...options });

/**
 * 创建频道分组
 *
 * 在指定服务器中创建一个新的频道分组分类
 */
export const postApiServersByServerIdChannelGroups = <ThrowOnError extends boolean = false>(
  options: Options<PostApiServersByServerIdChannelGroupsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiServersByServerIdChannelGroupsResponses,
    PostApiServersByServerIdChannelGroupsErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}/channel-groups",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 硬删除频道分组
 *
 * 物理删除特定的单个分组，所拥有的频道自关联会被级联设空(null)
 */
export const deleteApiChannelGroupsByGroupId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiChannelGroupsByGroupIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiChannelGroupsByGroupIdResponses,
    DeleteApiChannelGroupsByGroupIdErrors,
    ThrowOnError
  >({ url: "/api/channel-groups/{groupId}", ...options });

/**
 * 修改频道分组
 *
 * 更新指定频道分组的名称或排序标记权重值
 */
export const putApiChannelGroupsByGroupId = <ThrowOnError extends boolean = false>(
  options: Options<PutApiChannelGroupsByGroupIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiChannelGroupsByGroupIdResponses,
    PutApiChannelGroupsByGroupIdErrors,
    ThrowOnError
  >({
    url: "/api/channel-groups/{groupId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 批量排序频道分组
 *
 * 批量快速对指定服务器下的所有频道分组排序权重进行多条调整
 */
export const putApiServersByServerIdChannelGroupsSort = <ThrowOnError extends boolean = false>(
  options: Options<PutApiServersByServerIdChannelGroupsSortData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiServersByServerIdChannelGroupsSortResponses,
    PutApiServersByServerIdChannelGroupsSortErrors,
    ThrowOnError
  >({
    url: "/api/servers/{serverId}/channel-groups/sort",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 注册受控物理机器机台
 *
 * 在所属的服务器空间下新注册一个工作机器实例，并发放 Machine 校验主密钥 （sk_slock_*）
 */
export const postApiMachinesRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiMachinesRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiMachinesRegisterResponses,
    PostApiMachinesRegisterErrors,
    ThrowOnError
  >({
    url: "/api/machines/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 吊销物理机台
 *
 * 吊销指定物理机台的鉴权凭证
 */
export const postApiMachinesByMachineIdRevoke = <ThrowOnError extends boolean = false>(
  options: Options<PostApiMachinesByMachineIdRevokeData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiMachinesByMachineIdRevokeResponses, unknown, ThrowOnError>(
    { url: "/api/machines/{machineId}/revoke", ...options },
  );

/**
 * 获取机器下的智能体列表
 *
 * 获取绑定在特定服务器空间的所有智能体实例
 */
export const getApiServersByServerIdAgents = <ThrowOnError extends boolean = false>(
  options: Options<GetApiServersByServerIdAgentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiServersByServerIdAgentsResponses, unknown, ThrowOnError>({
    url: "/api/servers/{serverId}/agents",
    ...options,
  });

/**
 * 注册智能体
 *
 * 由绑定在目标服务器机台上的运行守护进程上报并注册/更新智能体实例
 */
export const postApiAgentsRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAgentsRegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAgentsRegisterResponses,
    PostApiAgentsRegisterErrors,
    ThrowOnError
  >({
    url: "/api/agents/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取频道消息
 *
 * 获取特定聊天频道内的历史消息消息列表
 */
export const getApiChannelsByChannelIdMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetApiChannelsByChannelIdMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiChannelsByChannelIdMessagesResponses, unknown, ThrowOnError>(
    { url: "/api/channels/{channelId}/messages", ...options },
  );

/**
 * 发送频道消息
 *
 * 在指定频道中发送文本消息内容，可附带父级节点及 Mentions 信息
 */
export const postApiChannelsByChannelIdMessages = <ThrowOnError extends boolean = false>(
  options: Options<PostApiChannelsByChannelIdMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiChannelsByChannelIdMessagesResponses,
    PostApiChannelsByChannelIdMessagesErrors,
    ThrowOnError
  >({
    url: "/api/channels/{channelId}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 获取消息会话线程
 *
 * 获取针对单条消息展开的回复会话链
 */
export const getApiMessagesByMessageIdThread = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMessagesByMessageIdThreadData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiMessagesByMessageIdThreadResponses, unknown, ThrowOnError>({
    url: "/api/messages/{messageId}/thread",
    ...options,
  });

/**
 * Sign in with a social provider
 */
export const socialSignIn = <ThrowOnError extends boolean = false>(
  options: Options<SocialSignInData, ThrowOnError>,
) =>
  (options.client ?? client).post<SocialSignInResponses, SocialSignInErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/sign-in/social",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiAuthCallbackById = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthCallbackByIdData, ThrowOnError>,
) =>
  (options?.client ?? client).get<unknown, GetApiAuthCallbackByIdErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/callback/{id}",
    ...options,
  });

export const postApiAuthCallbackById = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthCallbackByIdData, ThrowOnError>,
) =>
  (options?.client ?? client).post<unknown, PostApiAuthCallbackByIdErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/callback/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Get the current session
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options?: Options<GetSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/get-session",
    ...options,
  });

/**
 * Get the current session
 */
export const getSession2 = <ThrowOnError extends boolean = false>(
  options?: Options<GetSession2Data, ThrowOnError>,
) =>
  (options?.client ?? client).post<GetSession2Responses, GetSession2Errors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/get-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Sign out the current user
 */
export const signOut = <ThrowOnError extends boolean = false>(
  options?: Options<SignOutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<SignOutResponses, SignOutErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/sign-out",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = <ThrowOnError extends boolean = false>(
  options?: Options<SignUpWithEmailAndPasswordData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    SignUpWithEmailAndPasswordResponses,
    SignUpWithEmailAndPasswordErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/sign-up/email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Sign in with email and password
 */
export const signInEmail = <ThrowOnError extends boolean = false>(
  options: Options<SignInEmailData, ThrowOnError>,
) =>
  (options.client ?? client).post<SignInEmailResponses, SignInEmailErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/sign-in/email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset the password for a user
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify the current user's password
 */
export const verifyPassword = <ThrowOnError extends boolean = false>(
  options: Options<VerifyPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<VerifyPasswordResponses, VerifyPasswordErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/verify-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify the email of the user
 */
export const getApiAuthVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAuthVerifyEmailData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiAuthVerifyEmailResponses,
    GetApiAuthVerifyEmailErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/verify-email",
    ...options,
  });

/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = <ThrowOnError extends boolean = false>(
  options?: Options<SendVerificationEmailData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    SendVerificationEmailResponses,
    SendVerificationEmailErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/send-verification-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

export const changeEmail = <ThrowOnError extends boolean = false>(
  options: Options<ChangeEmailData, ThrowOnError>,
) =>
  (options.client ?? client).post<ChangeEmailResponses, ChangeEmailErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/change-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the password of the user
 */
export const changePassword = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update the current session
 */
export const updateSession = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).post<UpdateSessionResponses, UpdateSessionErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/update-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Update the current user
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateUserData, ThrowOnError>,
) =>
  (options?.client ?? client).post<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/update-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Delete the user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteUserData, ThrowOnError>,
) =>
  (options?.client ?? client).post<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/delete-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Send a password reset email to the user
 */
export const requestPasswordReset = <ThrowOnError extends boolean = false>(
  options: Options<RequestPasswordResetData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RequestPasswordResetResponses,
    RequestPasswordResetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/request-password-reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordCallbackData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ResetPasswordCallbackResponses,
    ResetPasswordCallbackErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/reset-password/{token}",
    ...options,
  });

/**
 * List all active sessions for the user
 */
export const listUserSessions = <ThrowOnError extends boolean = false>(
  options?: Options<ListUserSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListUserSessionsResponses, ListUserSessionsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/list-sessions",
    ...options,
  });

/**
 * Revoke a single session
 */
export const postApiAuthRevokeSession = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthRevokeSessionData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiAuthRevokeSessionResponses,
    PostApiAuthRevokeSessionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/revoke-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Revoke all sessions for the user
 */
export const postApiAuthRevokeSessions = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthRevokeSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiAuthRevokeSessionsResponses,
    PostApiAuthRevokeSessionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/revoke-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Revoke all other sessions for the user except the current one
 */
export const postApiAuthRevokeOtherSessions = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthRevokeOtherSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiAuthRevokeOtherSessionsResponses,
    PostApiAuthRevokeOtherSessionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/revoke-other-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Link a social account to the user
 */
export const linkSocialAccount = <ThrowOnError extends boolean = false>(
  options: Options<LinkSocialAccountData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LinkSocialAccountResponses,
    LinkSocialAccountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/link-social",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all accounts linked to the user
 */
export const listUserAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<ListUserAccountsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListUserAccountsResponses, ListUserAccountsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/list-accounts",
    ...options,
  });

/**
 * Callback to complete user deletion with verification token
 */
export const getApiAuthDeleteUserCallback = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthDeleteUserCallbackData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiAuthDeleteUserCallbackResponses,
    GetApiAuthDeleteUserCallbackErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/delete-user/callback",
    ...options,
  });

/**
 * Unlink an account
 */
export const postApiAuthUnlinkAccount = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthUnlinkAccountData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthUnlinkAccountResponses,
    PostApiAuthUnlinkAccountErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/unlink-account",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh the access token using a refresh token
 */
export const postApiAuthRefreshToken = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRefreshTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthRefreshTokenResponses,
    PostApiAuthRefreshTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/refresh-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postApiAuthGetAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthGetAccessTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthGetAccessTokenResponses,
    PostApiAuthGetAccessTokenErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/get-access-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the account info provided by the provider
 */
export const getApiAuthAccountInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthAccountInfoData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiAuthAccountInfoResponses,
    GetApiAuthAccountInfoErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/account-info",
    ...options,
  });

/**
 * Check if the API is working
 */
export const getApiAuthOk = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthOkData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiAuthOkResponses, GetApiAuthOkErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/ok",
    ...options,
  });

/**
 * Displays an error page
 */
export const getApiAuthError = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthErrorData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiAuthErrorResponses, GetApiAuthErrorErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/error",
    ...options,
  });
