// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {});
};

export type GetApiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api";
};

export type GetApiResponses = {
  /**
   * API 连通正常
   */
  200: unknown;
};

export type GetApiServersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/servers";
};

export type GetApiServersResponses = {
  /**
   * 成功获取服务器列表
   */
  200: unknown;
};

export type PostApiServersData = {
  body: {
    name: string;
    slug?: string;
  };
  path?: never;
  query?: never;
  url: "/api/servers";
};

export type PostApiServersErrors = {
  /**
   * 输入校验未通过
   */
  400: unknown;
};

export type PostApiServersResponses = {
  /**
   * 服务器创建完成
   */
  200: {
    name: string;
    slug?: string;
  };
};

export type PostApiServersResponse = PostApiServersResponses[keyof PostApiServersResponses];

export type GetApiServersByServerIdChannelsData = {
  body?: never;
  path: {
    serverId: string;
  };
  query?: never;
  url: "/api/servers/{serverId}/channels";
};

export type GetApiServersByServerIdChannelsResponses = {
  /**
   * 成功获取频道列表
   */
  200: unknown;
};

export type PostApiServersByServerIdChannelsData = {
  body: {
    name: string;
  };
  path: {
    serverId: string;
  };
  query?: never;
  url: "/api/servers/{serverId}/channels";
};

export type PostApiServersByServerIdChannelsErrors = {
  /**
   * 输入校验未通过
   */
  400: unknown;
};

export type PostApiServersByServerIdChannelsResponses = {
  /**
   * 频道创建完成
   */
  200: {
    name: string;
  };
};

export type PostApiServersByServerIdChannelsResponse =
  PostApiServersByServerIdChannelsResponses[keyof PostApiServersByServerIdChannelsResponses];

export type PostApiMachinesRegisterData = {
  body: {
    serverId: string;
    label: string;
  };
  path?: never;
  query?: never;
  url: "/api/machines/register";
};

export type PostApiMachinesRegisterErrors = {
  /**
   * 输入校验未通过
   */
  400: unknown;
};

export type PostApiMachinesRegisterResponses = {
  /**
   * 物理机台注册成功并返回密钥对
   */
  200: {
    serverId: string;
    label: string;
  };
};

export type PostApiMachinesRegisterResponse =
  PostApiMachinesRegisterResponses[keyof PostApiMachinesRegisterResponses];

export type PostApiMachinesByMachineIdRevokeData = {
  body?: never;
  path: {
    machineId: string;
  };
  query?: never;
  url: "/api/machines/{machineId}/revoke";
};

export type PostApiMachinesByMachineIdRevokeResponses = {
  /**
   * 吊销成功
   */
  200: unknown;
};

export type GetApiServersByServerIdAgentsData = {
  body?: never;
  path: {
    serverId: string;
  };
  query?: never;
  url: "/api/servers/{serverId}/agents";
};

export type GetApiServersByServerIdAgentsResponses = {
  /**
   * 成功获取智能体列表
   */
  200: unknown;
};

export type PostApiAgentsRegisterData = {
  body: {
    name: string;
    displayName: string;
    runtime: "claude" | "opencode";
  };
  path?: never;
  query?: never;
  url: "/api/agents/register";
};

export type PostApiAgentsRegisterErrors = {
  /**
   * 输入校验未通过
   */
  400: unknown;
};

export type PostApiAgentsRegisterResponses = {
  /**
   * 智能体注册或更新成功
   */
  200: {
    name: string;
    displayName: string;
    runtime: "claude" | "opencode";
  };
};

export type PostApiAgentsRegisterResponse =
  PostApiAgentsRegisterResponses[keyof PostApiAgentsRegisterResponses];

export type GetApiChannelsByChannelIdMessagesData = {
  body?: never;
  path: {
    channelId: string;
  };
  query?: never;
  url: "/api/channels/{channelId}/messages";
};

export type GetApiChannelsByChannelIdMessagesResponses = {
  /**
   * 成功获取历史消息
   */
  200: unknown;
};

export type PostApiChannelsByChannelIdMessagesData = {
  body: {
    content: string;
    parentId?: string | null;
    replyTo?: string | null;
    senderId?: string;
    senderType?: "human" | "agent" | "system";
    mentions?: Array<string>;
  };
  path: {
    channelId: string;
  };
  query?: never;
  url: "/api/channels/{channelId}/messages";
};

export type PostApiChannelsByChannelIdMessagesErrors = {
  /**
   * 参数检验未通过 / 防止循环触发超出深度限制
   */
  400: unknown;
};

export type PostApiChannelsByChannelIdMessagesResponses = {
  /**
   * 消息投放成功并返回带有 UUID 的消息对象
   */
  200: {
    content: string;
    parentId?: string | null;
    replyTo?: string | null;
    senderId?: string;
    senderType?: "human" | "agent" | "system";
    mentions?: Array<string>;
  };
};

export type PostApiChannelsByChannelIdMessagesResponse =
  PostApiChannelsByChannelIdMessagesResponses[keyof PostApiChannelsByChannelIdMessagesResponses];

export type GetApiMessagesByMessageIdThreadData = {
  body?: never;
  path: {
    messageId: string;
  };
  query?: never;
  url: "/api/messages/{messageId}/thread";
};

export type GetApiMessagesByMessageIdThreadResponses = {
  /**
   * 成功获取话题线程消息
   */
  200: unknown;
};
